
use master;

DROP TABLE IF EXISTS Gas_Stations;
DROP TABLE IF EXISTS Boat_Repairs;
DROP TABLE IF EXISTS Shipyards;
DROP TABLE IF EXISTS Tour_Stops;
DROP TABLE IF EXISTS Locations;

DROP TABLE IF EXISTS ContractClients;
DROP TABLE IF EXISTS Clients;
DROP TABLE IF EXISTS Contract;
DROP TABLE IF EXISTS Offer;

DROP TABLE IF EXISTS PeopleBatch;

DROP TABLE IF EXISTS Batch;
DROP TABLE IF EXISTS Boat;
DROP TABLE IF EXISTS Tour;
DROP TABLE IF EXISTS People;
